### ISSUE TITLE
Issue: Clean platform_visualization_script

### ISSUE THREAD

**Issue by EJwalker13** [NASA-IMPACT/platform-visualization#1]
## Overview
During the second phase of Take Flight with CASEI we wrote code to visualize aircraft navigation data for NASA campaigns. This script was quickly thrown together and as best practice we should clean it for future developers. 

## Tasks
- [x] Run the code
- [x] See where the data is read in
- [x] Remove any unused libraries
- [x] Remove any commented out lines
- [x] Add comments where needed
- [x] Make PR request of committed changes

**Comment by anabellebr22** [comment]
Done :) !
