### ISSUE TITLE
Issue: Replace current map with terrain map

### ISSUE THREAD

**Issue by EJwalker13** [NASA-IMPACT/platform-visualization#11]
## Overview
We need to ensure that our maps are consistent with the format on the CASEI website. If you look at the bounding box map for any campaign it uses a terrain base map. To keep that consistency we are going to add the terrain_map code to the platform_visualization script

Just for reference a base map represents geographic the area and what we overlay our data on. It provides geospatial context for the map user. 

## Tasks
- [x] Add terrain_map code to platform_visualization script
- [x] Check if the aircraft data or ground site data is being plotted onto the terrain map
- [x] Remove previous map (the simple map that we are using)
- [x] Visualize all data on the map and save each figure

**Comment by anabellebr22** [comment]
Everything was visualized onto the new terrain map.  I have the screenshots saved in a folder on my desktop
