### ISSUE TITLE
Visualize LISTOS

### ISSUE THREAD

**Issue by EJwalker13** [NASA-IMPACT/platform-visualization#13]
## Overview
After successfully visualizing tracks for campaigns with aircraft platforms we need to visualize other types of platforms. The LISTOS campaign contained ground site radars and we need to visualize this platforms to present that we can visualize multiple types of campaigns instead of just aircraft. Once completed this will wrap up the visualization process.

Links to get started for finding code to visualize point data: 
https://stackoverflow.com/questions/52131975/plotting-point-data-in-cartopy

https://uoftcoders.github.io/studyGroup/lessons/python/cartography/lesson/

## Tasks
- [x] Find code to visualize point data
- [x] Create a NEW FILE inside the code for visualizing point data in the dev branch
- [x]  Visualize over the terrain basemap
- [x] Create PR request
- [x] Merge into main

**Comment by anabellebr22** [comment]
Created PR request
