### ISSUE TITLE
Map Pagination

### ISSUE THREAD

**Issue by EJwalker13** [NASA-IMPACT/platform-visualization#14]
## Overview
The next task is to write code that executes pagination for the maps that you have created. Pagination or paging, is the process of dividing a document into discrete pages, either electronic pagers or printed pages. We are going to put each map on a different page which will separate them based upon each flight. 

Also slack Stephanie to let her know that I assigned your next task and what you are doing. 

## Tasks
- [ ] Find pagination code
- [ ] Run executable code that separates each map for the three campaigns
- [ ] Create pull request on dev so that it can merge into main
