### ISSUE TITLE
Issue: Find navigation data

### ISSUE THREAD

**Issue by EJwalker13** [NASA-IMPACT/platform-visualization#2]
## Overview
The first step of our methodology is to find the data that we want to visualize for each campaign. The data we are looking for is usually called navigation data and is stored in .ICARTT files. To help you find this data you can use the https://search.earthdata.nasa.gov/search website.

## Tasks
- [x] Make Earthdata Search account
- [x] Query the selected campaigns
- [x] Download navigation data for SMODE, IMPACTS, LISTOS, OLYMPEX 
- [x] Add data to dev

**Comment by anabellebr22** [comment]
Finding Navigation Data Notes:

Finding Olympex Data:
- go to CASEI website
- look at what platforms were used for Olympex
    - DC-8, ER-2, Citation for aircraft
- go to earth data search and query air based platforms
- search for data that says either platform in the title
- for DC-8 : GPM Ground Validation Navigation Data DC-8 OLYMPEX V1
- for ER-2:  GPM Ground Validation NASA ER-2 Navigation Data OLYMPEX V1
- for Citation : GPM Ground Validation UND Citation Navigation Data OLYMPEX V1

Finding SMODE Data: COULD NOT FIND DATA
- go to CASEI website
- look at what platforms were used for SMODE
    - B-200, Twin Otter, G-III
- go to earth data search and query air based platforms
- search for data that says either platform in the title
- for B-200; 
- for Twin Otter:
- for G-III:


Finding IMPACTS Data: 
- go to CASEI website
- look at what platforms were used for SMODE
    - P-3, ER-2
- go to earth data search and query air based platforms
- search for data that says either platform in the title
- for P-3:  P-3 Meteorological and Navigation Data IMPACTS V1
- for ER-2 : ER-2 Navigation Data IMPACTS V1


Finding LISTOS Data: COULD NOT FIND DATA
- go to CASEI website
- look at what platforms were used for SMODE
    - Long Ez
- go to earth data search and query air based platforms
- search for data that says either platform in the title
- for Long Ez: COULD NOT FIND DATA

**Comment by EJwalker13** [comment]
Found the nav data but need to find a replacement campaign for SMODE

**Comment by EJwalker13** [comment]
Found the nav data but need to find a replacement campaign for SMODE
